#!/bin/bash

function createUac() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/uac.auto.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/uac.auto.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:7054 --caname ca_uac --tls.certfiles "${PWD}/organizations/fabric-ca/ca_uac/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-7054-ca_uac.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-7054-ca_uac.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-7054-ca_uac.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-7054-ca_uac.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/uac.auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy uac's CA cert to uac's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/uac.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ca_uac/ca-cert.pem" "${PWD}/organizations/peerOrganizations/uac.auto.com/msp/tlscacerts/ca.crt"

  # Copy uac's CA cert to uac's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/uac.auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ca_uac/ca-cert.pem" "${PWD}/organizations/peerOrganizations/uac.auto.com/tlsca/tlsca.uac.auto.com-cert.pem"

  # Copy uac's CA cert to uac's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/uac.auto.com/ca"
  cp "${PWD}/organizations/fabric-ca/ca_uac/ca-cert.pem" "${PWD}/organizations/peerOrganizations/uac.auto.com/ca/ca.uac.auto.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca_uac --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/ca_uac/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca_uac --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/ca_uac/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca_uac --id.name uacadmin --id.secret uacadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ca_uac/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca_uac -M "${PWD}/organizations/peerOrganizations/uac.auto.com/peers/peer0.uac.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ca_uac/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/uac.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/uac.auto.com/peers/peer0.uac.auto.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:7054 --caname ca_uac -M "${PWD}/organizations/peerOrganizations/uac.auto.com/peers/peer0.uac.auto.com/tls" --enrollment.profile tls --csr.hosts peer0.uac.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ca_uac/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/uac.auto.com/peers/peer0.uac.auto.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/uac.auto.com/peers/peer0.uac.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/uac.auto.com/peers/peer0.uac.auto.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/uac.auto.com/peers/peer0.uac.auto.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/uac.auto.com/peers/peer0.uac.auto.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/uac.auto.com/peers/peer0.uac.auto.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:7054 --caname ca_uac -M "${PWD}/organizations/peerOrganizations/uac.auto.com/users/User1@uac.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ca_uac/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/uac.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/uac.auto.com/users/User1@uac.auto.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://uacadmin:uacadminpw@localhost:7054 --caname ca_uac -M "${PWD}/organizations/peerOrganizations/uac.auto.com/users/Admin@uac.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ca_uac/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/uac.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/uac.auto.com/users/Admin@uac.auto.com/msp/config.yaml"
}

function createUstim() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/ustim.auto.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/ustim.auto.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:8054 --caname ca_ustim --tls.certfiles "${PWD}/organizations/fabric-ca/ca_ustim/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-8054-ca_ustim.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-8054-ca_ustim.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-8054-ca_ustim.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-8054-ca_ustim.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/ustim.auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy ustim's CA cert to ustim's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/ustim.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ca_ustim/ca-cert.pem" "${PWD}/organizations/peerOrganizations/ustim.auto.com/msp/tlscacerts/ca.crt"

  # Copy ustim's CA cert to ustim's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/ustim.auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ca_ustim/ca-cert.pem" "${PWD}/organizations/peerOrganizations/ustim.auto.com/tlsca/tlsca.ustim.auto.com-cert.pem"

  # Copy ustim's CA cert to ustim's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/ustim.auto.com/ca"
  cp "${PWD}/organizations/fabric-ca/ca_ustim/ca-cert.pem" "${PWD}/organizations/peerOrganizations/ustim.auto.com/ca/ca.ustim.auto.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca_ustim --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/ca_ustim/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca_ustim --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/ca_ustim/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca_ustim --id.name ustimadmin --id.secret ustimadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ca_ustim/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca_ustim -M "${PWD}/organizations/peerOrganizations/ustim.auto.com/peers/peer0.ustim.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ca_ustim/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/ustim.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/ustim.auto.com/peers/peer0.ustim.auto.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:8054 --caname ca_ustim -M "${PWD}/organizations/peerOrganizations/ustim.auto.com/peers/peer0.ustim.auto.com/tls" --enrollment.profile tls --csr.hosts peer0.ustim.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ca_ustim/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/ustim.auto.com/peers/peer0.ustim.auto.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/ustim.auto.com/peers/peer0.ustim.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/ustim.auto.com/peers/peer0.ustim.auto.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/ustim.auto.com/peers/peer0.ustim.auto.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/ustim.auto.com/peers/peer0.ustim.auto.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/ustim.auto.com/peers/peer0.ustim.auto.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:8054 --caname ca_ustim -M "${PWD}/organizations/peerOrganizations/ustim.auto.com/users/User1@ustim.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ca_ustim/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/ustim.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/ustim.auto.com/users/User1@ustim.auto.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://ustimadmin:ustimadminpw@localhost:8054 --caname ca_ustim -M "${PWD}/organizations/peerOrganizations/ustim.auto.com/users/Admin@ustim.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ca_ustim/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/ustim.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/ustim.auto.com/users/Admin@ustim.auto.com/msp/config.yaml"
}


function createUp() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/peerOrganizations/up.auto.com/

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/peerOrganizations/up.auto.com/

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:11054 --caname ca_up --tls.certfiles "${PWD}/organizations/fabric-ca/ca_up/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-11054-ca_up.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-11054-ca_up.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-11054-ca_up.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-11054-ca_up.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/peerOrganizations/up.auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy up's CA cert to up's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/peerOrganizations/up.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ca_up/ca-cert.pem" "${PWD}/organizations/peerOrganizations/up.auto.com/msp/tlscacerts/ca.crt"

  # Copy up's CA cert to up's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/up.auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ca_up/ca-cert.pem" "${PWD}/organizations/peerOrganizations/up.auto.com/tlsca/tlsca.up.auto.com-cert.pem"

  # Copy up's CA cert to up's /ca directory (for use by clients)
  mkdir -p "${PWD}/organizations/peerOrganizations/up.auto.com/ca"
  cp "${PWD}/organizations/fabric-ca/ca_up/ca-cert.pem" "${PWD}/organizations/peerOrganizations/up.auto.com/ca/ca.up.auto.com-cert.pem"

  echo "Registering peer0"
  set -x
  fabric-ca-client register --caname ca_up --id.name peer0 --id.secret peer0pw --id.type peer --tls.certfiles "${PWD}/organizations/fabric-ca/ca_up/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering user"
  set -x
  fabric-ca-client register --caname ca_up --id.name user1 --id.secret user1pw --id.type client --tls.certfiles "${PWD}/organizations/fabric-ca/ca_up/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the org admin"
  set -x
  fabric-ca-client register --caname ca_up --id.name upadmin --id.secret upadminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ca_up/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the peer0 msp"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca_up -M "${PWD}/organizations/peerOrganizations/up.auto.com/peers/peer0.up.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ca_up/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/up.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/up.auto.com/peers/peer0.up.auto.com/msp/config.yaml"

  echo "Generating the peer0-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://peer0:peer0pw@localhost:11054 --caname ca_up -M "${PWD}/organizations/peerOrganizations/up.auto.com/peers/peer0.up.auto.com/tls" --enrollment.profile tls --csr.hosts peer0.up.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ca_up/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the peer's tls directory that are referenced by peer startup config
  cp "${PWD}/organizations/peerOrganizations/up.auto.com/peers/peer0.up.auto.com/tls/tlscacerts/"* "${PWD}/organizations/peerOrganizations/up.auto.com/peers/peer0.up.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/peerOrganizations/up.auto.com/peers/peer0.up.auto.com/tls/signcerts/"* "${PWD}/organizations/peerOrganizations/up.auto.com/peers/peer0.up.auto.com/tls/server.crt"
  cp "${PWD}/organizations/peerOrganizations/up.auto.com/peers/peer0.up.auto.com/tls/keystore/"* "${PWD}/organizations/peerOrganizations/up.auto.com/peers/peer0.up.auto.com/tls/server.key"

  echo "Generating the user msp"
  set -x
  fabric-ca-client enroll -u https://user1:user1pw@localhost:11054 --caname ca_up -M "${PWD}/organizations/peerOrganizations/up.auto.com/users/User1@up.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ca_up/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/up.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/up.auto.com/users/User1@up.auto.com/msp/config.yaml"

  echo "Generating the org admin msp"
  set -x
  fabric-ca-client enroll -u https://upadmin:upadminpw@localhost:11054 --caname ca_up -M "${PWD}/organizations/peerOrganizations/up.auto.com/users/Admin@up.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ca_up/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/peerOrganizations/up.auto.com/msp/config.yaml" "${PWD}/organizations/peerOrganizations/up.auto.com/users/Admin@up.auto.com/msp/config.yaml"
}


function createOrderer() {
  echo "Enrolling the CA admin"
  mkdir -p organizations/ordererOrganizations/auto.com

  export FABRIC_CA_CLIENT_HOME=${PWD}/organizations/ordererOrganizations/auto.com

  set -x
  fabric-ca-client enroll -u https://admin:adminpw@localhost:9054 --caname ca-orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo 'NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: peer
  AdminOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: admin
  OrdererOUIdentifier:
    Certificate: cacerts/localhost-9054-ca-orderer.pem
    OrganizationalUnitIdentifier: orderer' > "${PWD}/organizations/ordererOrganizations/auto.com/msp/config.yaml"

  # Since the CA serves as both the organization CA and TLS CA, copy the org's root cert that was generated by CA startup into the org level ca and tlsca directories

  # Copy orderer org's CA cert to orderer org's /msp/tlscacerts directory (for use in the channel MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/auto.com/msp/tlscacerts/tlsca.auto.com-cert.pem"

  # Copy orderer org's CA cert to orderer org's /tlsca directory (for use by clients)
  mkdir -p "${PWD}/organizations/ordererOrganizations/auto.com/tlsca"
  cp "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem" "${PWD}/organizations/ordererOrganizations/auto.com/tlsca/tlsca.auto.com-cert.pem"

  echo "Registering orderer"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name orderer --id.secret ordererpw --id.type orderer --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Registering the orderer admin"
  set -x
  fabric-ca-client register --caname ca-orderer --id.name ordererAdmin --id.secret ordererAdminpw --id.type admin --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  echo "Generating the orderer msp"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/auto.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp/config.yaml"

  echo "Generating the orderer-tls certificates, use --csr.hosts to specify Subject Alternative Names"
  set -x
  fabric-ca-client enroll -u https://orderer:ordererpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls" --enrollment.profile tls --csr.hosts orderer.auto.com --csr.hosts localhost --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  # Copy the tls CA cert, server cert, server keystore to well known file names in the orderer's tls directory that are referenced by orderer startup config
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/ca.crt"
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/signcerts/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/server.crt"
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/keystore/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/server.key"

  # Copy orderer org's CA cert to orderer's /msp/tlscacerts directory (for use in the orderer MSP definition)
  mkdir -p "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp/tlscacerts"
  cp "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/tls/tlscacerts/"* "${PWD}/organizations/ordererOrganizations/auto.com/orderers/orderer.auto.com/msp/tlscacerts/tlsca.auto.com-cert.pem"

  echo "Generating the admin msp"
  set -x
  fabric-ca-client enroll -u https://ordererAdmin:ordererAdminpw@localhost:9054 --caname ca-orderer -M "${PWD}/organizations/ordererOrganizations/auto.com/users/Admin@auto.com/msp" --tls.certfiles "${PWD}/organizations/fabric-ca/ordererOrg/ca-cert.pem"
  { set +x; } 2>/dev/null

  cp "${PWD}/organizations/ordererOrganizations/auto.com/msp/config.yaml" "${PWD}/organizations/ordererOrganizations/auto.com/users/Admin@auto.com/msp/config.yaml"
}

createUac
createUstim
createUp
createOrderer